"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { io, type Socket } from "socket.io-client";

type Member = { userId: string; displayName: string; status: string; ready: boolean; score: number; guessCount: number };
type Room = { code: string; hostId: string; phase: "lobby" | "countdown" | "playing" | "round_result" | "finished"; roundNumber: number; roundCount: number; roundEndsAt?: number; isPublic?: boolean; members: Member[] };
type Player = { id: string; canonicalName: string; currentOrLastTeam: string };
const WS_URL = process.env.NEXT_PUBLIC_WS_URL ?? "http://localhost:3001";

export default function VersusPage() {
  const socket = useRef<Socket | null>(null); const [room, setRoom] = useState<Room | null>(null); const [error, setError] = useState(""); const [joinCode, setJoinCode] = useState(""); const [me, setMe] = useState<string | null>(null); const [players, setPlayers] = useState<Player[]>([]); const [query, setQuery] = useState(""); const [result, setResult] = useState(""); const [publicRooms, setPublicRooms] = useState<Room[]>([]); const [waiting, setWaiting] = useState(false);
  useEffect(() => { fetch("/api/auth/me").then((response) => response.json()).then((data) => { if (!data.user) { setError("联机对战需要登录账号。"); return; } setMe(data.user.id); return fetch("/api/auth/realtime-ticket", { method: "POST" }); }).then((response) => response?.json()).then((data) => { if (!data?.ticket?.token) return; const client = io(WS_URL, { auth: { ticket: data.ticket.token }, transports: ["websocket"] }); socket.current = client; client.on("connect", () => { client.emit("room:list-public", {}, (reply: { rooms?: Room[] }) => setPublicRooms(reply.rooms ?? [])); const code = localStorage.getItem("valo_versus_room"); if (code) client.emit("room:reconnect", { code }, (reply: { room?: Room }) => reply.room && setRoom(reply.room)); }); client.on("connect_error", (event) => setError(event.message)); client.on("room:state", (nextRoom: Room) => { localStorage.setItem("valo_versus_room", nextRoom.code); setRoom(nextRoom); }); client.on("match:found", (event) => { localStorage.setItem("valo_versus_room", event.room.code); setWaiting(false); setRoom(event.room); }); client.on("room:guess-result", (event) => setResult(`${event.canonicalName}: ${event.isCorrect ? "正确" : "继续猜测"} ${event.points ? `+${event.points}` : ""}`)); client.on("room:round-result", (event) => setResult(`本回合答案：${event.target.canonicalName}`)); }).catch(() => setError("无法建立实时连接。")); return () => { socket.current?.disconnect(); }; }, []);
  useEffect(() => { if (!query.trim()) { setPlayers([]); return; } const timer = setTimeout(() => fetch(`/api/players?q=${encodeURIComponent(query)}`).then((response) => response.json()).then(setPlayers), 180); return () => clearTimeout(timer); }, [query]);
  const candidates = useMemo(() => players.slice(0, 8), [players]);
  const emit = (event: string, payload: object) => new Promise<any>((resolve) => socket.current?.emit(event, payload, resolve));
  async function create(isPublic = false) { const reply = await emit("room:create", { isPublic, maxPlayers: 2, roundCount: 1, roundDurationSeconds: 60 }); if (reply?.error) setError(reply.error); else setRoom(reply.room); }
  async function join() { const reply = await emit("room:join", { code: joinCode.trim().toUpperCase() }); if (reply?.error) setError(reply.error); else setRoom(reply.room); }
  async function match() { const reply = await emit("match:join", { maxPlayers: 2, roundCount: 1, roundDurationSeconds: 60 }); if (reply?.error) setError(reply.error); else if (reply?.waiting) setWaiting(true); else setRoom(reply.room); }
  async function cancelMatch() { await emit("match:cancel", { maxPlayers: 2, roundCount: 1, roundDurationSeconds: 60 }); setWaiting(false); }
  async function ready() { if (!room) return; const reply = await emit("room:ready", { code: room.code, ready: !room.members.find((member) => member.userId === me)?.ready }); if (reply?.error) setError(reply.error); }
  async function start() { if (!room) return; const reply = await emit("room:start", { code: room.code }); if (reply?.error) setError(reply.error); }
  async function guess(playerId: string, name: string) { if (!room) return; const reply = await emit("room:guess", { code: room.code, playerId }); if (reply?.error) setError(reply.error); else { setResult(`已提交 ${name}`); setQuery(""); } }
  async function nextRound() { if (!room) return; const reply = await emit("room:next-round", { code: room.code }); if (reply?.error) setError(reply.error); }
  if (error && !me) return <main className="game-shell"><p className="form-error">{error}</p><a href="/login">前往登录</a></main>;
  return <main className="game-shell"><header className="game-header"><a href="/">VALO 一把</a><a href="/solo">单人对战</a></header><section className="game-intro"><p className="eyebrow">VERSUS BETA</p><h1>联机对战</h1></section>{!room && <section className="versus-entry">{waiting ? <button onClick={cancelMatch}>取消匹配</button> : <button className="entry-button" onClick={match}>在线匹配</button>}<button className="entry-button" onClick={() => create(false)}>创建私密房间</button><button className="entry-button" onClick={() => create(true)}>创建公开房间</button><div><input value={joinCode} maxLength={6} onChange={(event) => setJoinCode(event.target.value.toUpperCase())} placeholder="6 位邀请码" /><button onClick={join}>加入房间</button></div>{publicRooms.length > 0 && <div className="public-rooms">{publicRooms.map((item) => <button key={item.code} onClick={() => { setJoinCode(item.code); void emit("room:join", { code: item.code }).then((reply) => reply?.room && setRoom(reply.room)); }}>公开房 {item.code} · {item.members.length} 人</button>)}</div>}</section>}{room && <section className="game-board"><div className="game-meta"><strong>房间 {room.code}</strong><span>{room.phase} · 回合 {room.roundNumber}/{room.roundCount}</span></div><div className="member-list">{room.members.map((member) => <div key={member.userId}><strong>{member.displayName}{member.userId === room.hostId ? " (房主)" : ""}</strong><span>{member.status} · {member.ready ? "已准备" : "未准备"} · {member.score} 分</span></div>)}</div>{room.phase === "lobby" && <div className="room-actions"><button onClick={ready}>切换准备</button>{room.hostId === me && <button onClick={start}>开始对局</button>}</div>}{room.phase === "playing" && <div className="guess-box"><p>剩余猜测：{room.members.find((member) => member.userId === me)?.guessCount ?? 0} / 8</p><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索选手" />{candidates.map((player) => <button className="candidate" key={player.id} onClick={() => guess(player.id, player.canonicalName)}>{player.canonicalName} <small>{player.currentOrLastTeam}</small></button>)}</div>}{room.phase === "round_result" && room.hostId === me && <button onClick={nextRound}>下一回合</button>}{room.phase === "finished" && <section className="result-panel"><p>对局结束</p>{[...room.members].sort((a, b) => b.score - a.score).map((member, index) => <p key={member.userId}>{index + 1}. {member.displayName} · {member.score} 分</p>)}</section>}{result && <p className="success-message">{result}</p>}{error && <p className="form-error">{error}</p>}</section>}</main>;
}
