map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

upstream valo_web {
  server web:3000;
}

upstream valo_api {
  server api:3001;
}

server {
  listen 80;
  server_name zmjjkk33.top www.zmjjkk33.top;

  client_max_body_size 2m;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  http2 on;
  server_name zmjjkk33.top www.zmjjkk33.top;

  ssl_certificate /etc/letsencrypt/live/zmjjkk33.top/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/zmjjkk33.top/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 10m;

  client_max_body_size 2m;

  location /socket.io/ {
    proxy_pass http://valo_api;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
  }

  location / {
    proxy_pass http://valo_web;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }
}
