"use client";

import { useEffect, useMemo, useState } from "react";

type Difficulty = "beginner" | "easy" | "full";
type Player = { id: string; canonicalName: string; countryCode: string; region: string; primaryRole: string; currentOrLastTeam: string };
type Guess = { canonicalName: string; isCorrect: boolean; comparison: Record<string, string> };
type Attempt = { id: string; difficulty: Difficulty; status: "active" | "won" | "lost" | "abandoned"; guessCount: number; score?: number | null };
const labels: Record<string, string> = { region: "赛区", country: "国籍", primaryRole: "位置", currentOrLastTeam: "队伍", championsTitles: "冠军赛", mastersTitles: "大师赛", heroTop3: "英雄 Top 3" };

function guestId() { const key = "valo_guest_id"; let value = localStorage.getItem(key); if (!value) { value = crypto.randomUUID(); localStorage.setItem(key, value); } return value; }

export default function SoloPage() {
  const [attempt, setAttempt] = useState<Attempt | null>(null); const [players, setPlayers] = useState<Player[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Player | null>(null); const [guesses, setGuesses] = useState<Guess[]>([]); const [result, setResult] = useState<{ target: { canonicalName: string }; score: number } | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { const savedAttemptId = localStorage.getItem("valo_solo_attempt_id"); if (savedAttemptId) fetch(`/api/solo/attempts/${savedAttemptId}?guestId=${guestId()}`).then((response) => response.ok ? response.json() : null).then((data) => { if (data) { setAttempt(data.attempt); setGuesses(data.guesses); setResult(data.result ?? null); } else localStorage.removeItem("valo_solo_attempt_id"); }).catch(() => undefined); }, []);
  useEffect(() => { if (!query.trim()) { setPlayers([]); return; } const controller = new AbortController(); const timer = window.setTimeout(() => fetch(`/api/players?q=${encodeURIComponent(query)}`, { signal: controller.signal }).then((response) => response.json()).then(setPlayers).catch(() => undefined), 180); return () => { controller.abort(); window.clearTimeout(timer); }; }, [query]);
  const candidates = useMemo(() => players.slice(0, 8), [players]);
  async function start(difficulty: Difficulty) { setBusy(true); setError(""); try { const response = await fetch("/api/solo/attempts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ difficulty, guestId: guestId() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); localStorage.setItem("valo_solo_attempt_id", data.attempt.id); setAttempt(data.attempt); setGuesses([]); setResult(null); setSelected(null); setQuery(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "无法开始对局。"); } finally { setBusy(false); } }
  async function submit() { if (!attempt || !selected) return; setBusy(true); setError(""); try { const response = await fetch(`/api/solo/attempts/${attempt.id}/guesses`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ playerId: selected.id, guestId: guestId() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setGuesses((items) => [...items, data.guess]); setAttempt(data.attempt); setResult(data.result ?? null); if (data.result) localStorage.removeItem("valo_solo_attempt_id"); setSelected(null); setQuery(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "提交失败。"); } finally { setBusy(false); } }
  async function abandon() { if (!attempt || !confirm("确定要放弃本局吗？")) return; const response = await fetch(`/api/solo/attempts/${attempt.id}/abandon`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ guestId: guestId() }) }); const data = await response.json(); if (response.ok) { localStorage.removeItem("valo_solo_attempt_id"); setAttempt(data.attempt); setResult(data.result); } else setError(data.error ?? "放弃失败。"); }
  return <main className="game-shell"><header className="game-header"><a href="/">VALO 一把</a><a href="/login">登录或注册</a></header><section className="game-intro"><p className="eyebrow">SOLO ALPHA</p><h1>单人对战</h1><p>根据职业选手资料缩小范围。每局最多 8 次猜测。</p></section>{!attempt && <section className="difficulty-grid">{(["beginner", "easy", "full"] as Difficulty[]).map((difficulty) => <button key={difficulty} disabled={busy} onClick={() => start(difficulty)}><strong>{{ beginner: "入门", easy: "简单", full: "完整" }[difficulty]}</strong><span>开始随机对局</span></button>)}</section>}{attempt && <section className="game-board"><div className="game-meta"><span>{attempt.difficulty === "beginner" ? "入门" : attempt.difficulty === "easy" ? "简单" : "完整"}</span><strong>{attempt.guessCount} / 8 次猜测</strong>{attempt.status === "active" && <button className="text-button" onClick={abandon}>放弃</button>}</div>{attempt.status === "active" && <div className="guess-box"><label>搜索选手<input autoFocus value={query} onChange={(event) => { setQuery(event.target.value); setSelected(null); }} placeholder="输入选手 ID 或姓名" /></label>{query && !selected && <div className="candidate-list">{candidates.map((player) => <button key={player.id} onClick={() => { setSelected(player); setQuery(player.canonicalName); }}>{player.canonicalName}<small>{player.currentOrLastTeam}</small></button>)}</div>}{selected && <button className="submit-guess" disabled={busy} onClick={submit}>猜测 {selected.canonicalName}</button>}</div>}{guesses.length > 0 && <div className="guess-history">{guesses.map((guess, index) => <article key={`${guess.canonicalName}-${index}`}><h2>{index + 1}. {guess.canonicalName} {guess.isCorrect ? "正确" : ""}</h2><div className="comparison-grid">{Object.entries(guess.comparison).map(([key, value]) => <span key={key} data-match={value}>{labels[key]}: {value === "exact" || value === "equal" ? "匹配" : value === "nearby" || value === "partial" ? "接近" : value === "higher" ? "更高" : value === "lower" ? "更低" : "不匹配"}</span>)}</div></article>)}</div>}{result && <section className="result-panel"><p>{attempt.status === "won" ? "猜对了" : attempt.status === "abandoned" ? "本局已放弃" : "本局结束"}</p><h2>答案：{result.target.canonicalName}</h2><strong>{result.score} 分</strong><button onClick={() => { setAttempt(null); setResult(null); }}>再来一局</button></section>}</section>}{error && <p className="form-error">{error}</p>}</main>;
}
